#!/usr/bin/env bash
# Bootstrap the Sail-Tracker Backlog Project (Projects v2) + custom fields.
# Captures IDs to scripts/.gh-project.env for the project-automation workflow.
# NOT idempotent — running twice creates a duplicate project. Run once.
set -euo pipefail

OWNER="${OWNER:-carlsendk}"
TITLE="${TITLE:-Sail-Tracker Backlog}"
ENV_FILE="$(dirname "$0")/.gh-project.env"

echo "Creating project '$TITLE' under $OWNER ..."
PROJECT_JSON=$(gh project create --owner "$OWNER" --title "$TITLE" --format json)
PROJECT_NUMBER=$(echo "$PROJECT_JSON" | jq -r '.number')
PROJECT_ID=$(echo "$PROJECT_JSON" | jq -r '.id')
PROJECT_URL=$(echo "$PROJECT_JSON" | jq -r '.url')
echo "  number=$PROJECT_NUMBER id=$PROJECT_ID"
echo "  url=$PROJECT_URL"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/gh-bootstrap-project.sh — do not edit by hand.
PROJECT_OWNER=$OWNER
PROJECT_NUMBER=$PROJECT_NUMBER
PROJECT_ID=$PROJECT_ID
PROJECT_URL=$PROJECT_URL
EOF

echo "Creating Tier field ..."
gh project field-create "$PROJECT_NUMBER" --owner "$OWNER" \
  --name "Tier" --data-type SINGLE_SELECT \
  --single-select-options "Phase-0,Infra-1,Infra-2,Infra-3,Infra-4,Tier-1,Tier-2,Tier-3,Tier-4,Tier-5,Tier-6,Tier-7" \
  >/dev/null

echo "Creating Domain field ..."
gh project field-create "$PROJECT_NUMBER" --owner "$OWNER" \
  --name "Domain" --data-type SINGLE_SELECT \
  --single-select-options "members,fleet,trips,equipment,qualifications,platform,backbone,cross-cutting,modules,infra" \
  >/dev/null

echo "Creating Estimate field ..."
gh project field-create "$PROJECT_NUMBER" --owner "$OWNER" \
  --name "Estimate" --data-type SINGLE_SELECT \
  --single-select-options "S,M,L" \
  >/dev/null

echo "Replacing default Status options (Todo/In Progress/Done) with our 6-state workflow ..."
# The built-in Status field exists but only has 3 default options. We replace them with
# our state machine (Backlog/Ready/In Progress/In Review/Blocked/Done) so the Kanban view
# reflects the agent workflow. This requires GraphQL — the gh CLI does not expose option
# editing on built-in fields.
STATUS_FIELD_ID=$(gh project field-list "$PROJECT_NUMBER" --owner "$OWNER" --format json --limit 50 \
  | jq -r '.fields[] | select(.name=="Status") | .id')

gh api graphql -f query='
mutation($fieldId:ID!) {
  updateProjectV2Field(input:{
    fieldId:$fieldId
    singleSelectOptions:[
      {name:"Backlog", color:GRAY, description:"Not yet ready for pickup"}
      {name:"Ready", color:GREEN, description:"Agent can pick up"}
      {name:"In Progress", color:YELLOW, description:"Agent actively working"}
      {name:"In Review", color:BLUE, description:"PR open"}
      {name:"Blocked", color:RED, description:"Needs human input"}
      {name:"Done", color:PURPLE, description:"Merged"}
    ]
  }) {
    projectV2Field { ... on ProjectV2SingleSelectField { id } }
  }
}' -f fieldId="$STATUS_FIELD_ID" >/dev/null

echo "Capturing field + option IDs ..."
FIELDS_JSON=$(gh project field-list "$PROJECT_NUMBER" --owner "$OWNER" --format json --limit 50)

# Append field IDs (only for our SINGLE_SELECT fields, not built-in number/title fields)
echo "" >> "$ENV_FILE"
echo "# Field IDs" >> "$ENV_FILE"
for field in Tier Domain Estimate Status; do
  field_id=$(echo "$FIELDS_JSON" | jq -r --arg n "$field" '.fields[] | select(.name==$n) | .id')
  echo "FIELD_ID_$(echo "$field" | tr '[:lower:]' '[:upper:]')=$field_id" >> "$ENV_FILE"
done

# Status field option IDs (built-in field; we map state:* labels to these in the workflow)
echo "" >> "$ENV_FILE"
echo "# Status field option IDs" >> "$ENV_FILE"
echo "$FIELDS_JSON" \
  | jq -r '.fields[] | select(.name=="Status") | .options[] | "STATUS_OPT_\(.name | ascii_upcase | gsub("[^A-Z0-9]"; "_"))=\(.id)"' \
  >> "$ENV_FILE"

echo ""
echo "Done. Captured to $ENV_FILE:"
cat "$ENV_FILE"
